# Generated by Django 5.1.3 on 2024-12-20 02:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_postsresponses_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
